sudo: required
language: node_js

services:
  - docker

branches:
  only:
  - master

install: docker build -t kabbageinc/kalemail .
script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
after_success: docker push kabbageinc/kalemail
after_script: docker rmi -f kabbageinc/kalemail
