sudo: required

services:
  - docker

script: docker build -t kabbageinc/kalemail .
before_deploy: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy: docker push kabbageinc/kalemail
after_deploy: docker rmi -f kabbageinc/kalemail
