version: '3'

services:
  app:
    build: '.'
    container_name: 'mailkatcher'
    ports:
      - '25:25'
      - '3000:3000'
    volumes:
      - './ssl:/ssl'
    env_file: './mailkatcher.env'
    links:
      - db
    depends_on:
      - db
  db:
    image: 'mysql'
    container_name: 'mailkatcher-db'
    expose:
      - 3306
    ports:
      - "6033:3306"
    env_file: './mailkatcher-db.env'
    volumes:
      - ./data:/var/lib/mysql
      - ./scripts/sql:/docker-entrypoint-initdb.d
